"""Initial enterprise schema migration

Revision ID: 91a6af212dfd
Revises: 
Create Date: 2026-08-29 23:00:15.949451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a6af212dfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_orm_category', table_name='metrics_orm')
    op.drop_index('ix_metrics_orm_id', table_name='metrics_orm')
    op.drop_table('metrics_orm')
    op.drop_index('ix_inventory_orm_id', table_name='inventory_orm')
    op.drop_index('ix_inventory_orm_item_id', table_name='inventory_orm')
    op.drop_table('inventory_orm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_orm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_orm_item_id', 'inventory_orm', ['item_id'], unique=1)
    op.create_index('ix_inventory_orm_id', 'inventory_orm', ['id'], unique=False)
    op.create_table('metrics_orm',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('revenue', sa.FLOAT(), nullable=True),
    sa.Column('expenses', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_orm_id', 'metrics_orm', ['id'], unique=False)
    op.create_index('ix_metrics_orm_category', 'metrics_orm', ['category'], unique=False)
    # ### end Alembic commands ###
